site_name: Let's Java! Java 基础教程
site_author: 'PegasusWang'
repo_name: 'LetsJava'
repo_url: 'https://github.com/hikaricp/spring-family'

copyright: 'Copyright &copy; 2019 - 2021 杨佳畅'

theme:
 name: material
 favicon: svg/school.svg
 logo: svg/logo.svg
 icon:
  repo: fontawesome/brands/github-alt
 palette:
  primary: black
  accent: amber
 font:
  text: 'Roboto'
  code: 'Roboto Mono'

extra_javascript:
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
 social:
  - icon: fontawesome/brands/github
    link: https://github.com/hikaricp

nav:
 - 简介: index.md